### ISSUE TITLE
Just a note

### ISSUE THREAD

**Issue by m4heshd** [valnoxy/wadark#1]
This looks good and glad you managed to keep this project alive. Code looks very clean too. I appreciate that you gave me credit.

Few suggestions:

- Try to add Mac support soon. Almost half of the users from my project are Mac users.
- Append the original license from my repo to your license.
- Add a link to the original project in the credits

All these will improve your work and keep your project much cleaner. Other than that, keep up the good work. 👍🏽

**Comment by valnoxy** [comment]
Thanks! I will do that. ✌😊
